name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Swift version
        run: swift --version

      - name: Check xcresulttool availability
        run: xcrun xcresulttool version

      - name: Build
        run: swift build

      - name: Run Tests
        timeout-minutes: 5
        run: swift test --verbose
